/* 
Programmer: Nate
 Date: November 10 2024
 Program Name: Airline Points
 Program Description: This program uses arrays to simulate a matching game.
 * A grid of cards will be displayed and the user is to select 2 cards at a time
 * looking for matching cards. The goal of this game is to see how quickly
 * the user can find all the matches.
*/
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nate.powell.airline.points;

import java.util.ArrayList;
/**
 *
 * @author Nate
 */
public class AirlinePointsUI extends javax.swing.JFrame {
    ArrayList<Passenger> airlinepoints = new ArrayList<Passenger>();
    /**
     * Creates new form AirlinePointsUI
     */
    public AirlinePointsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintitle = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        firstnameinput = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameinput = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        pointsbutton = new javax.swing.JButton();
        removebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        week1input = new javax.swing.JTextField();
        week2input = new javax.swing.JTextField();
        week3input = new javax.swing.JTextField();
        week4input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        output1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maintitle.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(0, 51, 255));
        maintitle.setText("Point Tracker");

        firstnameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstnameLabel.setText("First Name");

        lastnameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastnameLabel.setText("Last Name");

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        displaybutton.setText("Display");
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });

        pointsbutton.setText("Points");
        pointsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsbuttonActionPerformed(evt);
            }
        });

        removebutton.setBackground(new java.awt.Color(255, 0, 0));
        removebutton.setText("Remove");
        removebutton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                removebuttonStateChanged(evt);
            }
        });
        removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Week1 points");

        jLabel2.setText("Week 2points");

        jLabel3.setText("Week 3 points");

        jLabel4.setText("Week 4 points");

        output1.setEditable(false);
        output1.setColumns(20);
        output1.setRows(5);
        jScrollPane1.setViewportView(output1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addbutton)
                                .addGap(18, 18, 18)
                                .addComponent(displaybutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pointsbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removebutton))
                            .addComponent(firstnameLabel)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lastnameinput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addComponent(firstnameinput, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lastnameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maintitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(week1input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(week2input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(week3input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(week4input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(jLabel1)
                    .addComponent(week1input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(week2input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(jLabel3)
                    .addComponent(week3input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnameinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(week4input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(displaybutton)
                    .addComponent(pointsbutton)
                    .addComponent(removebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
    String firstname, lastname; // Declare variables 
    String week1, week2, week3, week4;
   
    int week1points; 
    int week2points; 
    int week3points; 
    int week4points;
    // Get the user input
    firstname = firstnameinput.getText();
    lastname = lastnameinput.getText();
    week1 = week1input.getText();
    week2 = week2input.getText();
    week3 = week3input.getText();
    week4 = week4input.getText();

    // Check if the firstname and lastname fields are empty
    if (firstname.isEmpty() || lastname.isEmpty()) {
        output1.setText("Please fill out all the fields");
        return; // Stop further execution if names are missing
    }

    // Check if any of the week points fields are empty
    if (week1.isEmpty() || week2.isEmpty() || week3.isEmpty() || week4.isEmpty()) {
        output1.setText("Please fill out all the week fields");
        return; // Stop further execution if any week field is empty
    }

    // Try to parse the week points as integers and calculate total points
    try {
        week1points = Integer.parseInt(week1);
        week2points = Integer.parseInt(week2);
        week3points = Integer.parseInt(week3);
        week4points = Integer.parseInt(week4);
        
        
    } catch (NumberFormatException e) {
        output1.setText("Please enter valid numbers for the points.");
        week1input.setText("");
        week2input.setText("");
        week3input.setText("");
        week4input.setText("");
        return; // Stop further execution if points are not valid numbers
    }

    // Add the new Passenger points into the system
    try {
        Passenger newPassenger = new Passenger(firstname,lastname,week1points,week2points,week3points,week4points);
        
        airlinepoints.add(newPassenger); // Assuming airlinepoints is a collection like ArrayList
        
        // Clear input fields after successful addition
        week1input.setText("");
        week2input.setText("");
        week3input.setText("");
        week4input.setText("");
        firstnameinput.setText("");
        lastnameinput.setText("");
        
        firstnameinput.requestFocus();

        output1.setText("Passenger added successfully!"); // Optional message
        
    } catch (Exception e) {
        output1.setText("There has been an error while processing your information. Please try again.");
        week1input.setText("");
        week2input.setText("");
        week3input.setText("");
        week4input.setText("");
        
        firstnameinput.setText("");
        lastnameinput.setText("");
        firstnameinput.requestFocus();

    }
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
    // Clear the previous information from the output area
    output1.setText("");

    // Check if the list is empty
    if (airlinepoints.isEmpty()) {
        output1.setText("No passengers to display.");
    } else {
        // Display passenger details
        for (int i = 0; i < airlinepoints.size(); i++) {
            Passenger passenger = airlinepoints.get(i);

            // Calculate total points by summing weekly points
            int totalpoints = passenger.week1Points + passenger.week2Points + passenger.week3Points + passenger.week4Points;

            // Determine bonus eligibility
            int totalWithBonus = totalpoints; // Initialize total with no bonus
            String bonusMessage = "No";      // Default message for bonus eligibility

            if (totalpoints > 5000) {
                totalWithBonus += 1000;      // Add 1,000 bonus points
                bonusMessage = "Yes";       // Update message for bonus eligibility
            }

            // Append passenger details to the output
            output1.append((i + 1) + ". " 
                           + passenger.firstName + " " + passenger.lastName 
                           + " - Total Points: " + totalpoints 
                           + " - Bonus Qualified: " + bonusMessage 
                           + " - Total with Bonus: " + totalWithBonus + "\n");
        }
    }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void pointsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsbuttonActionPerformed
    String firstname, lastname;
    int totalpoints = 0;
    // Get the user input for the name
    firstname = firstnameinput.getText();
    lastname = lastnameinput.getText();

    // Check if the firstname and lastname fields are empty
    if (firstname.isEmpty() || lastname.isEmpty()) {
        output1.setText("Please enter both first name and last name to search.");
        return;
    }
    
    // Search for the passenger in the airlinepoints collection
    for (Passenger passenger : airlinepoints) {
        if (passenger.firstName.equalsIgnoreCase(firstname) &&
            passenger.lastName.equalsIgnoreCase(lastname)) {
            // Display the total points
            totalpoints = (passenger.week1Points + passenger.week2Points + passenger.week3Points + passenger.week4Points);
            output1.setText("Total points for " + firstname + " " + lastname + ": " + totalpoints);
            firstnameinput.setText("");
            lastnameinput.setText("");
            firstnameinput.requestFocus();
        } else {
            // If passenger is not found
            output1.setText("Passenger not found. Please check the name and try again.");
        }
    }


    }//GEN-LAST:event_pointsbuttonActionPerformed

    private void removebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebuttonActionPerformed
    // Get the first and last name inputs for identifying the passenger to remove
    String firstname = firstnameinput.getText();
    String lastname = lastnameinput.getText();

    // Clear output for new messages
    output1.setText("");

    // Validate inputs
    if (firstname.isEmpty() || lastname.isEmpty()) {
        output1.setText("Please enter the passenger's first and last name to remove.");
        return;
    }

    // Flag to track if the passenger is found
    boolean passengerFound = false;

    // Iterate through the list to find the passenger
    for (int i = 0; i < airlinepoints.size(); i++) {
        Passenger passenger = airlinepoints.get(i);
        if (passenger.firstName.equalsIgnoreCase(firstname) && passenger.lastName.equalsIgnoreCase(lastname)) {
            passengerFound = true;

            // Ask the user to confirm removal
            if (!output1.getText().contains("Are you sure you want to remove")) {
                output1.setText("Passenger found: " + passenger.firstName + " " + passenger.lastName 
                                + ". Are you sure you want to remove this passenger? Press 'Remove' again to confirm.");
                return;
            } else {
                // Remove the passenger on the second press
                airlinepoints.remove(i);
                output1.setText("Passenger " + passenger.firstName + " " + passenger.lastName + " has been successfully removed.");
                break;
            }
        }
    }

    // If no matching passenger was found
    if (!passengerFound) {
        output1.setText("Passenger not found. Please check the name and try again.");
    }

    // Clear the input fields for reuse
    firstnameinput.setText("");
    lastnameinput.setText("");
    firstnameinput.requestFocus();
    }//GEN-LAST:event_removebuttonActionPerformed

    private void removebuttonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_removebuttonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_removebuttonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlinePointsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlinePointsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton displaybutton;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameinput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameinput;
    private javax.swing.JLabel maintitle;
    private javax.swing.JTextArea output1;
    private javax.swing.JButton pointsbutton;
    private javax.swing.JButton removebutton;
    private javax.swing.JTextField week1input;
    private javax.swing.JTextField week2input;
    private javax.swing.JTextField week3input;
    private javax.swing.JTextField week4input;
    // End of variables declaration//GEN-END:variables
class Passenger {
    String firstName, lastName;
   
    int week1Points, week2Points,week3Points,week4Points;
    Passenger( String _firstName, String _lastName,int _week1Points, int _week2Points, int _week3Points, int _week4Points) {
        firstName = _firstName;
        lastName = _lastName;
        week1Points = _week1Points;
        week2Points = _week2Points;
        week3Points = _week3Points;
        week4Points = _week4Points;
     
 

}
}}
